<?php
/*
Plugin Name: Social It
Plugin URI: http://gaut.am/bbpress/plugins/social-it/
Description: Social It adds a (X)HTML compliant list of social bookmarking icons to topics, front page, tags, etc. See <a href="admin-base.php?plugin=socialit_settings_page">configuration panel</a> for more settings. This plugin is inspired from the <a href="http://sexybookmarks.net/">SexyBookmarks plugin for Wordpress</a>. This plugin is also compatible with <a href="http://bbpress.org/plugins/topic/support-forum/">Support Forum plugin</a>.
Version: 1.5
Author: Gautam
Author URI: http://gaut.am/
*/

/**
 * @package Social It
 * @subpackage Main Section
 * @author Gautam Gupta (www.gaut.am)
 * @link http://gaut.am/bbpress/plugins/social-it/
 * @license GNU General Public License version 3 (GPLv3):
 * http://www.opensource.org/licenses/gpl-3.0.html
 */

/* Create Text Domain For Translations */
bb_load_plugin_textdomain( 'social-it', dirname( __FILE__ ) . '/languages' ); 

/*
 * Defines
 */
define( 'SOCIALIT_VER',		'1.6-dev'			); /* Version */
define( 'SOCIALIT_OPTIONS',	'SocialIt'			); /* Option Name */
define( 'SOCIALIT_PLUGDIR',	dirname( __FILE__ ) . '/'	); /* Absolute Path to Plugin directory */
define( 'SOCIALIT_PLUGPATH',	bb_get_plugin_uri( bb_plugin_basename( __FILE__ ) ) ); /* Plugin URL */
define( 'SOCIALIT_RELDIR',	'/' . trim( str_replace( array( trim( BB_PATH, "/\\" ), "\\" ), array( "", "/" ), dirname( __FILE__ ) ), ' /\\' ) ); /* Relative Path, needed by Sprite Gen */

/* Load JSON functins if they are not present */
if ( !class_exists( 'SERVICES_JSON' ) ) { 
	if ( !function_exists( 'json_decode' ) ) {
		function json_decode( $content, $assoc = false ) {
			require_once( 'includes/JSON.php' );
			$json = ( $assoc ) ? new Services_JSON( SERVICES_JSON_LOOSE_TYPE ) : new Services_JSON;
			return $json->decode( $content );
		}
	}
	
	if ( !function_exists( 'json_encode' ) ) {
		function json_encode( $content ) {
			require_once( 'includes/JSON.php' );
			$json = new Services_JSON;
			return $json->encode( $content );
		}
	}
}

require_once( 'includes/common.php' ); /* Common data, needed in admin and public section */

/**
 * Options
 */
if ( !$socialit_plugopts = bb_get_option( SOCIALIT_OPTIONS ) ) {  /* Set the Options if they are not set */
	$socialit_plugopts = array(
		'reloption'	=> 'nofollow',
		'targetopt'	=> '_blank',
		'bgimg-yes'	=> 'yes',
		'bgimg'		=> 'caring',
		'shorty'	=> 'b2l',
		'shortyapi'	=> array(
			'snip'	=> array(
				'user'	=> '',
				'key'	=> ''
			),
			'bitly'	=> array(
				'user'	=> '',
				'key'	=> ''
			),
			'supr'	=> array(
				'chk'	=> 0,
				'user'	=> '',
				'key'	=> ''
			),
			'trim'	=> array(
				'chk'	=> 0,
				'user'	=> '',
				'pass'	=> ''
			),
			'tinyarrow' => array(
				'chk'	=> 0,
				'user'	=> ''
			),
			'cligs'	=> array(
				'chk'	=> 0,
				'key'	=> ''
			),
		),
		'shorturls'	=> array(),
		'topic'		=> '1',
		'bookmark'	=> array_keys( $socialit_bookmarks_data ),
		'xtrastyle'	=> '',
		'feed'		=> '0',
		'expand'	=> '1',
		'autocenter'	=> '0',
		'ybuzzcat'	=> 'science',
		'ybuzzmed'	=> 'text',
		'twittcat'	=> 'Internet',
		'tweetconfig'	=> '${title} - ${short_link}', /* Custom configuration of tweet */
		'defaulttags'	=> 'Forum,Internet',
		'warn-choice'	=> '',
		'sfpnonres'	=> 'yes',
		'sfpres'	=> 'yes',
		'sfpnonsup'	=> 'yes',
		'mobile-hide'	=> 'yes',
		'custom-mods'	=> '',
		'scriptInFooter'=> '1',
		'custom-css'	=> '' /* Generated by Sprite Gen */
	);
	bb_update_option( SOCIALIT_OPTIONS, $socialit_plugopts );
}

/*
 * Require Admin/Public File
 */
if ( bb_is_admin() ) { /* Load admin.php file if it is the admin area */
	require_once( 'includes/admin.php' );
} else { /* Else load public.php file if it is the public area */
        require_once( 'includes/mobile.php' );
	require_once( 'includes/public.php' );
}